import json
from typing import Tuple, Dict, Any
from FormalLLM.lspec.parser import parse_spec

def parse_expr(expr_str: str):
    # Wrap the expression in a dummy specification to parse it using the existing grammar
    dummy_spec_str = f"Precondition: := {expr_str}.\nPostcondition: := true."
    spec = parse_spec(dummy_spec_str)
    return spec.precondition.expr

def parse_llm_response(response: str) -> Tuple[str, Dict[str, Any]]:
    # Remove markdown code blocks if any
    response = response.strip()
    if response.startswith("```json"):
        response = response[7:]
    elif response.startswith("```"):
        response = response[3:]
    if response.endswith("```"):
        response = response[:-3]
    response = response.strip()
            
    data = json.loads(response)
    law = data.get("law")
    raw_params = data.get("parameters", {})
    
    parsed_params = {}
    
    if law == "assignment":
        parsed_params["variable"] = raw_params.get("variable")
        parsed_params["expr"] = parse_expr(raw_params.get("expr", "0"))
    elif law == "sequential":
        parsed_params["intermediate"] = parse_expr(raw_params.get("intermediate", "true"))
    elif law == "alternation":
        parsed_params["guard"] = parse_expr(raw_params.get("guard", "true"))
    elif law == "iteration":
        parsed_params["guard"] = parse_expr(raw_params.get("guard", "true"))
        parsed_params["variant"] = parse_expr(raw_params.get("variant", "0"))
    elif law == "skip":
        pass
    else:
        raise ValueError(f"Unknown law generated by LLM: {law}")
        
    return law, parsed_params
